# Deep Learning applied to structured and time series data

In [0]:
!pip install pandas-summary
!pip install sklearn-pandas

In [0]:
#imports

import pandas as pd
import numpy as np
import sklearn

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

from IPython.display import HTML, display

from pandas_summary import DataFrameSummary
import re
import pickle
import math
import os

from sklearn_pandas import DataFrameMapper
from sklearn.preprocessing import LabelEncoder, Imputer, StandardScaler
from pandas.api.types import is_string_dtype, is_numeric_dtype
import warnings

## Import dataset

In [5]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive

In [6]:
ls

gdrive/  sample_data/

In [0]:
### Paths
HOME_PATH = '/content/gdrive/My Drive/rossman_project/'
DATA_PATH = os.path.join(HOME_PATH, 'data')

In [8]:
DATA_PATH

'/content/gdrive/My Drive/rossman_project/data'

In [0]:
table_names = ['train', 'store', 'store_states', 'state_names', 
               'googletrend', 'weather', 'test']

In [0]:
tables = [pd.read_csv(f'{DATA_PATH}{fname}.csv', low_memory=False) for fname in table_names]

In [0]:
zipped_tables = list(zip(table_names, tables))

## Exporatory data summary

In [0]:
for t in zipped_tables: display(f'Table: {t[0]}'), display(t[1].head())

'Table: train'

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

'Table: store'

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

'Table: store_states'

   Store State
0      1    HE
1      2    TH
2      3    NW
3      4    BE
4      5    SN

'Table: state_names'

           StateName State
0  BadenWuerttemberg    BW
1             Bayern    BY
2             Berlin    BE
3        Brandenburg    BB
4             Bremen    HB

'Table: googletrend'

             file                     week  trend
0  Rossmann_DE_SN  2012-12-02 - 2012-12-08     96
1  Rossmann_DE_SN  2012-12-09 - 2012-12-15     95
2  Rossmann_DE_SN  2012-12-16 - 2012-12-22     91
3  Rossmann_DE_SN  2012-12-23 - 2012-12-29     48
4  Rossmann_DE_SN  2012-12-30 - 2013-01-05     67

'Table: weather'

,file,Date,Max_TemperatureC,Mean_TemperatureC,Min_TemperatureC,Dew_PointC,MeanDew_PointC,Min_DewpointC,Max_Humidity,Mean_Humidity,...,Max_VisibilityKm,Mean_VisibilityKm,Min_VisibilitykM,Max_Wind_SpeedKm_h,Mean_Wind_SpeedKm_h,Max_Gust_SpeedKm_h,Precipitationmm,CloudCover,Events,WindDirDegrees
0,NordrheinWestfalen,2013-01-01,8,4,2,7,5,1,94,87,...,31.0,12.0,4.0,39,26,58.0,5.08,6.0,Rain,215
1,NordrheinWestfalen,2013-01-02,7,4,1,5,3,2,93,85,...,31.0,14.0,10.0,24,16,NaN,0.00,6.0,Rain,225
2,NordrheinWestfalen,2013-01-03,11,8,6,10,8,4,100,93,...,31.0,8.0,2.0,26,21,NaN,1.02,7.0,Rain,240
3,NordrheinWestfalen,2013-01-04,9,9,8,9,9,8,100,94,...,11.0,5.0,2.0,23,14,NaN,0.25,7.0,Rain,263
4,NordrheinWestfalen,2013-01-05,8,8,7,8,7,6,100,94,...,10.0,6.0,3.0,16,10,NaN,0.00,7.0,Rain,268

'Table: test'

   Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday
0   1      1          4  2015-09-17   1.0      1            0              0
1   2      3          4  2015-09-17   1.0      1            0              0
2   3      7          4  2015-09-17   1.0      1            0              0
3   4      8          4  2015-09-17   1.0      1            0              0
4   5      9          4  2015-09-17   1.0      1            0              0

In [0]:
for t in zipped_tables: display(f'Table: {t[0]}'), display(DataFrameSummary(t[1]).summary())

'Table: train'

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
count,1.01721e+06,1.01721e+06,NaN,1.01721e+06,1.01721e+06,1.01721e+06,1.01721e+06,NaN,1.01721e+06
mean,558.43,3.99834,NaN,5773.82,633.146,0.830107,0.381515,NaN,0.178647
std,321.909,1.99739,NaN,3849.93,464.412,0.375539,0.485759,NaN,0.383056
min,1,1,NaN,0,0,0,0,NaN,0
25%,280,2,NaN,3727,405,1,0,NaN,0
50%,558,4,NaN,5744,609,1,0,NaN,0
75%,838,6,NaN,7856,837,1,1,NaN,0
max,1115,7,NaN,41551,7388,1,1,NaN,1
counts,1017209,1017209,1017209,1017209,1017209,1017209,1017209,1017209,1017209
uniques,1115,7,942,21734,4086,2,2,4,2
missing,0,0,0,0,0,0,0,0,0
missing_perc,0%,0%,0%,0%,0%,0%,0%,0%,0%
types,numeric,numeric,categorical,numeric,numeric,bool,bool,categorical,bool

'Table: store'

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
count,1115,NaN,NaN,1112,761,761,1115,571,571,NaN
mean,558,NaN,NaN,5404.9,7.2247,2008.67,0.512108,23.5954,2011.76,NaN
std,322.017,NaN,NaN,7663.17,3.21235,6.19598,0.500078,14.142,1.67494,NaN
min,1,NaN,NaN,20,1,1900,0,1,2009,NaN
25%,279.5,NaN,NaN,717.5,4,2006,0,13,2011,NaN
50%,558,NaN,NaN,2325,8,2010,1,22,2012,NaN
75%,836.5,NaN,NaN,6882.5,10,2013,1,37,2013,NaN
max,1115,NaN,NaN,75860,12,2015,1,50,2015,NaN
counts,1115,1115,1115,1112,761,761,1115,571,571,571
uniques,1115,4,3,654,12,23,2,24,7,3
missing,0,0,0,3,354,354,0,544,544,544
missing_perc,0%,0%,0%,0.27%,31.75%,31.75%,0%,48.79%,48.79%,48.79%
types,numeric,categorical,categorical,numeric,numeric,numeric,bool,numeric,numeric,categorical

'Table: store_states'

                Store        State
count            1115          NaN
mean              558          NaN
std           322.017          NaN
min                 1          NaN
25%             279.5          NaN
50%               558          NaN
75%             836.5          NaN
max              1115          NaN
counts           1115         1115
uniques          1115           12
missing             0            0
missing_perc       0%           0%
types         numeric  categorical

'Table: state_names'

             StateName   State
count               16      16
unique              16      16
top             Bayern      SL
freq                 1       1
counts              16      16
uniques             16      16
missing              0       0
missing_perc        0%      0%
types           unique  unique

'Table: googletrend'

                     file         week    trend
count                 NaN          NaN     2072
mean                  NaN          NaN  63.8142
std                   NaN          NaN  12.6502
min                   NaN          NaN        0
25%                   NaN          NaN       55
50%                   NaN          NaN       64
75%                   NaN          NaN       72
max                   NaN          NaN      100
counts               2072         2072     2072
uniques                14          148       68
missing                 0            0        0
missing_perc           0%           0%       0%
types         categorical  categorical  numeric

'Table: weather'

,file,Date,Max_TemperatureC,Mean_TemperatureC,Min_TemperatureC,Dew_PointC,MeanDew_PointC,Min_DewpointC,Max_Humidity,Mean_Humidity,...,Max_VisibilityKm,Mean_VisibilityKm,Min_VisibilitykM,Max_Wind_SpeedKm_h,Mean_Wind_SpeedKm_h,Max_Gust_SpeedKm_h,Precipitationmm,CloudCover,Events,WindDirDegrees
count,NaN,NaN,15840,15840,15840,15840,15840,15840,15840,15840,...,15459,15459,15459,15840,15840,3604,15840,14667,NaN,15840
mean,NaN,NaN,14.6441,10.389,6.19899,8.58782,6.20581,3.62614,93.6596,74.2829,...,24.0576,12.2398,7.02516,22.7666,11.9722,48.8643,0.831718,5.55131,NaN,175.897
std,NaN,NaN,8.64601,7.37926,6.52639,6.24478,6.08677,6.12839,7.67853,13.4866,...,8.9768,5.06794,4.9806,8.98862,5.87284,13.027,2.51351,1.68771,NaN,101.589
min,NaN,NaN,-11,-13,-15,-14,-15,-73,44,30,...,0,0,0,3,2,21,0,0,NaN,-1
25%,NaN,NaN,8,4,1,4,2,-1,90.75,65,...,14,10,3,16,8,39,0,5,NaN,80
50%,NaN,NaN,15,11,7,9,7,4,94,76,...,31,11,7,21,11,48,0,6,NaN,202
75%,NaN,NaN,21,16,11,13,11,8,100,85,...,31,14,10,27,14,55,0.25,7,NaN,256
max,NaN,NaN,39,31,24,25,20,19,100,100,...,31,31,31,101,53,111,58.93,8,NaN,360
counts,15840,15840,15840,15840,15840,15840,15840,15840,15840,15840,...,15459,15459,15459,15840,15840,3604,15840,14667,11889,15840
uniques,16,990,51,45,40,40,36,40,53,71,...,24,32,24,44,29,47,41,9,21,362
missing,0,0,0,0,0,0,0,0,0,0,...,381,381,381,0,0,12236,0,1173,3951,0
missing_perc,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,...,2.41%,2.41%,2.41%,0%,0%,77.25%,0%,7.41%,24.94%,0%
types,categorical,categorical,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,...,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,categorical,numeric

'Table: test'

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday
count,41088,41088,41088,NaN,41077,41088,NaN,41088
mean,20544.5,555.9,3.97917,NaN,0.854322,0.395833,NaN,0.443487
std,11861.2,320.274,2.01548,NaN,0.352787,0.489035,NaN,0.496802
min,1,1,1,NaN,0,0,NaN,0
25%,10272.8,279.75,2,NaN,1,0,NaN,0
50%,20544.5,553.5,4,NaN,1,0,NaN,0
75%,30816.2,832.25,6,NaN,1,1,NaN,1
max,41088,1115,7,NaN,1,1,NaN,1
counts,41088,41088,41088,41088,41077,41088,41088,41088
uniques,41088,856,7,48,2,2,2,2
missing,0,0,0,0,11,0,0,0
missing_perc,0%,0%,0%,0%,0.03%,0%,0%,0%
types,numeric,numeric,numeric,categorical,bool,bool,bool,bool

## Data Cleaning / Feature Engineering

As a structured data problem, we necessarily have to go through all the cleaning and feature engineering, even though we're using a neural network.

In [0]:
len(tables)

7

In [0]:
train, store, store_states, state_names, googletrend, weather, test = tables

In [0]:
len(train),len(test)

(1017209, 41088)

We turn state Holidays to booleans, to make them more convenient for modeling. We can do calculations on pandas fields using notation very similar (often identical) to numpy.

In [0]:
train.StateHoliday = train.StateHoliday!='0'
test.StateHoliday = test.StateHoliday!='0'

`join_df` is a function for joining tables on specific fields. By default, we'll be doing a left outer join of `right` on the `left` argument using the given fields for each table.

Pandas does joins using the `merge` method. The `suffixes` argument describes the naming convention for duplicate fields. We've elected to leave the duplicate field names on the left untouched, and append a "\_y" to those on the right.

In [0]:
def join_df(left, right, left_on, right_on=None, suffix='_y'):
    if right_on is None: right_on = left_on
    return left.merge(right, how='left', left_on=left_on, right_on=right_on, suffixes=("", suffix))

Join weather/state names:

In [0]:
table_names

['train',
 'store',
 'store_states',
 'state_names',
 'googletrend',
 'weather',
 'test']

In [0]:
weather = join_df(weather, state_names, "file", "StateName")

In [0]:
googletrend['Date'] = googletrend.week.str.split(' - ', expand=True)[0]
googletrend['State'] = googletrend.file.str.split('_', expand=True)[2]
googletrend.loc[googletrend.State=='NI', "State"] = 'HB,NI'

The following extracts particular date fields from a complete datetime for the purpose of constructing categoricals.

You should *always* consider this feature extraction step when working with date-time. We'll add to every table with a date field.

In [0]:
def add_datepart(df, fldname, drop=True, time=False):
    "Helper function that adds columns relevant to a date in the column `fldname` of `df`."
    fld = df[fldname]
    fld_dtype = fld.dtype
    if isinstance(fld_dtype, pd.core.dtypes.dtypes.DatetimeTZDtype):
        fld_dtype = np.datetime64

    if not np.issubdtype(fld_dtype, np.datetime64):
        df[fldname] = fld = pd.to_datetime(fld, infer_datetime_format=True)
    targ_pre = re.sub('[Dd]ate$', '', fldname)
    attr = ['Year', 'Month', 'Week', 'Day', 'Dayofweek', 'Dayofyear',
            'Is_month_end', 'Is_month_start', 'Is_quarter_end', 'Is_quarter_start', 'Is_year_end', 'Is_year_start']
    if time: attr = attr + ['Hour', 'Minute', 'Second']
    for n in attr: df[targ_pre + n] = getattr(fld.dt, n.lower())
    df[targ_pre + 'Elapsed'] = fld.astype(np.int64) // 10 ** 9
    if drop: df.drop(fldname, axis=1, inplace=True)

In [0]:
add_datepart(weather, "Date", drop=False)
add_datepart(googletrend, "Date", drop=False)
add_datepart(train, "Date", drop=False)
add_datepart(test, "Date", drop=False)

The Google trends data has a special category for the whole of Germany - we'll pull that out so we can use it explicitly.

In [0]:
trend_de = googletrend[googletrend.file == 'Rossmann_DE']

In [0]:
store = join_df(store, store_states, "Store")
len(store[store.State.isnull()])

0

In [0]:
joined = join_df(train, store, "Store")
joined_test = join_df(test, store, "Store")
len(joined[joined.StoreType.isnull()]),len(joined_test[joined_test.StoreType.isnull()])

(0, 0)

In [0]:
joined = join_df(joined, googletrend, ["State","Year", "Week"])
joined_test = join_df(joined_test, googletrend, ["State","Year", "Week"])
len(joined[joined.trend.isnull()]),len(joined_test[joined_test.trend.isnull()])

(0, 0)

In [0]:
joined = joined.merge(trend_de, 'left', ["Year", "Week"], suffixes=('', '_DE'))
joined_test = joined_test.merge(trend_de, 'left', ["Year", "Week"], suffixes=('', '_DE'))
len(joined[joined.trend_DE.isnull()]),len(joined_test[joined_test.trend_DE.isnull()])

(0, 0)

In [0]:
joined = join_df(joined, weather, ["State","Date"])
joined_test = join_df(joined_test, weather, ["State","Date"])
len(joined[joined.Mean_TemperatureC.isnull()]),len(joined_test[joined_test.Mean_TemperatureC.isnull()])

(0, 0)

In [0]:
for df in (joined, joined_test):
    for c in df.columns:
        if c.endswith('_y'):
            df.drop(c, inplace=True, axis=1)

Next we'll fill in missing values to avoid complications with `NA`'s.

In [0]:
for df in (joined,joined_test):
    df['CompetitionOpenSinceYear'] = df.CompetitionOpenSinceYear.fillna(1900).astype(np.int32)
    df['CompetitionOpenSinceMonth'] = df.CompetitionOpenSinceMonth.fillna(1).astype(np.int32)
    df['Promo2SinceYear'] = df.Promo2SinceYear.fillna(1900).astype(np.int32)
    df['Promo2SinceWeek'] = df.Promo2SinceWeek.fillna(1).astype(np.int32)

Next we'll extract features "CompetitionOpenSince" and "CompetitionDaysOpen".

In [0]:
for df in (joined,joined_test):
    df["CompetitionOpenSince"] = pd.to_datetime(dict(year=df.CompetitionOpenSinceYear, 
                                                     month=df.CompetitionOpenSinceMonth, day=15))
    df["CompetitionDaysOpen"] = df.Date.subtract(df.CompetitionOpenSince).dt.days

In [0]:
joined.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,Year,...,Max_Wind_SpeedKm_h,Mean_Wind_SpeedKm_h,Max_Gust_SpeedKm_h,Precipitationmm,CloudCover,Events,WindDirDegrees,StateName,CompetitionOpenSince,CompetitionDaysOpen
0,1,5,2015-07-31,5263,555,1,1,False,1,2015,...,24,11,NaN,0.0,1.0,Fog,13,Hessen,2008-09-15,2510
1,2,5,2015-07-31,6064,625,1,1,False,1,2015,...,14,11,NaN,0.0,4.0,Fog,309,Thueringen,2007-11-15,2815
2,3,5,2015-07-31,8314,821,1,1,False,1,2015,...,14,5,NaN,0.0,2.0,Fog,354,NordrheinWestfalen,2006-12-15,3150
3,4,5,2015-07-31,13995,1498,1,1,False,1,2015,...,23,16,NaN,0.0,6.0,NaN,282,Berlin,2009-09-15,2145
4,5,5,2015-07-31,4822,559,1,1,False,1,2015,...,14,11,NaN,0.0,4.0,NaN,290,Sachsen,2015-04-15,107

We'll replace some erroneous / outlying data.

In [0]:
for df in (joined,joined_test):
    df.loc[df.CompetitionDaysOpen<0, "CompetitionDaysOpen"] = 0
    df.loc[df.CompetitionOpenSinceYear<1990, "CompetitionDaysOpen"] = 0

We add "CompetitionMonthsOpen" field, limiting the maximum to 2 years to limit number of unique categories.

In [0]:
for df in (joined,joined_test):
    df["CompetitionMonthsOpen"] = df["CompetitionDaysOpen"]//30
    df.loc[df.CompetitionMonthsOpen>24, "CompetitionMonthsOpen"] = 24
joined.CompetitionMonthsOpen.unique()

array([24,  3, 19,  9,  0, 16, 17,  7, 15, 22, 11, 13,  2, 23, 12,  4, 10,
        1, 14, 20,  8, 18,  6, 21,  5], dtype=int64)

Same process for Promo dates.

In [0]:
 df["CompetitionOpenSince"] = pd.to_datetime(dict(year=df.CompetitionOpenSinceYear, 
                                                     month=df.CompetitionOpenSinceMonth, day=15))

In [0]:
for df in (joined,joined_test):
    df['_Month'] = (df.Promo2SinceWeek*7 - 6) // 30 + 1
    df.loc[df._Month>12, "_Month"] = 12
    df.loc[df._Month<1, "_Month"] = 1
    df['_Day'] = (df.Promo2SinceWeek*7 - 6) - (df['_Month'] - 1)*30
    df.loc[df._Day>28, "_Day"] = 28
    df.loc[df._Day<1, "_Day"] = 1
    df['Promo2Since'] = pd.to_datetime(dict(year=df.Promo2SinceYear, month=df._Month, day=df._Day))
    df["Promo2Days"] = df.Date.subtract(df["Promo2Since"]).dt.days
    
    del df['_Month']
    del df['_Day']

In [0]:
for df in (joined,joined_test):
    df.loc[df.Promo2Days<0, "Promo2Days"] = 0
    df.loc[df.Promo2SinceYear<1990, "Promo2Days"] = 0
    df["Promo2Weeks"] = df["Promo2Days"]//7
    df.loc[df.Promo2Weeks<0, "Promo2Weeks"] = 0
    df.loc[df.Promo2Weeks>25, "Promo2Weeks"] = 25
    df.Promo2Weeks.unique()

In [0]:
joined.loc[0:5, ['Date','Promo', 'Promo2', 'Promo2SinceYear', 'Promo2SinceWeek', 'Promo2Since', 'Promo2Days']]

,Date,Promo,Promo2,Promo2SinceYear,Promo2SinceWeek,Promo2Since,Promo2Days
0,2015-07-31,1,0,1900,1,1900-01-01,0
1,2015-07-31,1,1,2010,13,2010-03-25,1954
2,2015-07-31,1,1,2011,14,2011-04-02,1581
3,2015-07-31,1,0,1900,1,1900-01-01,0
4,2015-07-31,1,0,1900,1,1900-01-01,0
5,2015-07-31,1,0,1900,1,1900-01-01,0

In [0]:
joined.to_pickle(f'{DATA_PATH}joined.pkl')
joined_test.to_pickle(f'{DATA_PATH}joined_test.pkl')

## Durations

It is common when working with time series data to extract data that explains relationships across rows as opposed to columns, e.g.:
* Running averages
* Time until next event
* Time since last event

This is often difficult to do with most table manipulation frameworks, since they are designed to work with relationships across columns. As such, we've created a class to handle this type of data.

We'll define a function `get_elapsed` for cumulative counting across a sorted dataframe. Given a particular field `fld` to monitor, this function will start tracking time since the last occurrence of that field. When the field is seen again, the counter is set to zero.

Upon initialization, this will result in datetime na's until the field is encountered. This is reset every time a new store is seen. We'll see how to use this shortly.

In [0]:
def get_elapsed(fld, pre):
    day1 = np.timedelta64(1, 'D')
    last_date = np.datetime64()
    last_store = 0
    res = []

    for s,v,d in zip(df.Store.values,df[fld].values, df.Date.values):
        if s != last_store:
            last_date = np.datetime64()
            last_store = s
        if v: last_date = d
        res.append(((d-last_date).astype('timedelta64[D]') / day1))
    df[pre+fld] = res

In [0]:
df.sort_values(['Store', 'Date']).head(10)

              Date  Store  Promo  StateHoliday  SchoolHoliday
1016095 2013-01-01      1      0          True              1
1014980 2013-01-02      1      0         False              1
1013865 2013-01-03      1      0         False              1
1012750 2013-01-04      1      0         False              1
1011635 2013-01-05      1      0         False              1
1010520 2013-01-06      1      0         False              1
1009405 2013-01-07      1      1         False              1
1008290 2013-01-08      1      1         False              1
1007175 2013-01-09      1      1         False              1
1006060 2013-01-10      1      1         False              1

We'll be applying this to a subset of columns:

In [0]:
columns = ["Date", "Store", "Promo", "StateHoliday", "SchoolHoliday"]

In [0]:
df = train[columns].append(test[columns])

Let's walk through an example.

Say we're looking at School Holiday. We'll first sort by Store, then Date, and then call `add_elapsed('SchoolHoliday', 'After')`:
This will apply to each row with School Holiday:
* A applied to every row of the dataframe in order of store and date
* Will add to the dataframe the days since seeing a School Holiday
* If we sort in the other direction, this will count the days until another holiday.

In [0]:
fld = 'SchoolHoliday'
df = df.sort_values(['Store', 'Date'])
get_elapsed(fld, 'After')
df = df.sort_values(['Store', 'Date'], ascending=[True, False])
get_elapsed(fld, 'Before')

We'll do this for two more fields.

In [0]:
fld = 'StateHoliday'
df = df.sort_values(['Store', 'Date'])
get_elapsed(fld, 'After')
df = df.sort_values(['Store', 'Date'], ascending=[True, False])
get_elapsed(fld, 'Before')

In [0]:
fld = 'Promo'
df = df.sort_values(['Store', 'Date'])
get_elapsed(fld, 'After')
df = df.sort_values(['Store', 'Date'], ascending=[True, False])
get_elapsed(fld, 'Before')

We're going to set the active index to Date.

In [0]:
df = df.set_index("Date")

Then set null values from elapsed field calculations to 0.

In [0]:
df.head()

,Store,Promo,StateHoliday,SchoolHoliday,AfterSchoolHoliday,BeforeSchoolHoliday,AfterStateHoliday,BeforeStateHoliday,AfterPromo,BeforePromo
Date,,,,,,,,,,
2015-09-17,1,1,False,0,13.0,NaN,105.0,NaN,0.0,0.0
2015-09-16,1,1,False,0,12.0,NaN,104.0,NaN,0.0,0.0
2015-09-15,1,1,False,0,11.0,NaN,103.0,NaN,0.0,0.0
2015-09-14,1,1,False,0,10.0,NaN,102.0,NaN,0.0,0.0
2015-09-13,1,0,False,0,9.0,NaN,101.0,NaN,9.0,-1.0

In [0]:
columns = ['SchoolHoliday', 'StateHoliday', 'Promo']

In [0]:
for o in ['Before', 'After']:
    for p in columns:
        a = o+p
        df[a] = df[a].fillna(0).astype(int)

Next we'll demonstrate window functions in pandas to calculate rolling quantities.

Here we're sorting by date (`sort_index()`) and counting the number of events of interest (`sum()`) defined in `columns` in the following week (`rolling()`), grouped by Store (`groupby()`). We do the same in the opposite direction.

In [0]:
df.head()

,Store,Promo,StateHoliday,SchoolHoliday,AfterSchoolHoliday,BeforeSchoolHoliday,AfterStateHoliday,BeforeStateHoliday,AfterPromo,BeforePromo
Date,,,,,,,,,,
2015-09-17,1,1,False,0,13,0,105,0,0,0
2015-09-16,1,1,False,0,12,0,104,0,0,0
2015-09-15,1,1,False,0,11,0,103,0,0,0
2015-09-14,1,1,False,0,10,0,102,0,0,0
2015-09-13,1,0,False,0,9,0,101,0,9,-1

In [0]:
bwd = df[['Store']+columns].sort_index().groupby("Store").rolling(7, min_periods=1).sum()

In [0]:
fwd = df[['Store']+columns].sort_index(ascending=False
                                      ).groupby("Store").rolling(7, min_periods=1).sum()

Next we want to drop the Store indices grouped together in the window function.

Often in pandas, there is an option to do this in place. This is time and memory efficient when working with large datasets.

In [0]:
bwd.drop('Store',1,inplace=True)
bwd.reset_index(inplace=True)

In [0]:
fwd.drop('Store',1,inplace=True)
fwd.reset_index(inplace=True)

In [0]:
df.reset_index(inplace=True)

Now we'll merge these values onto the df.

In [0]:
df = df.merge(bwd, 'left', ['Date', 'Store'], suffixes=['', '_bw'])
df = df.merge(fwd, 'left', ['Date', 'Store'], suffixes=['', '_fw'])

In [0]:
columns

['SchoolHoliday', 'StateHoliday', 'Promo']

In [0]:
df.drop(columns,1,inplace=True)

In [0]:
df.head()

,Date,Store,AfterSchoolHoliday,BeforeSchoolHoliday,AfterStateHoliday,BeforeStateHoliday,AfterPromo,BeforePromo,SchoolHoliday_bw,StateHoliday_bw,Promo_bw,SchoolHoliday_fw,StateHoliday_fw,Promo_fw
0,2015-09-17,1,13,0,105,0,0,0,0.0,0.0,4.0,0.0,0.0,1.0
1,2015-09-16,1,12,0,104,0,0,0,0.0,0.0,3.0,0.0,0.0,2.0
2,2015-09-15,1,11,0,103,0,0,0,0.0,0.0,2.0,0.0,0.0,3.0
3,2015-09-14,1,10,0,102,0,0,0,0.0,0.0,1.0,0.0,0.0,4.0
4,2015-09-13,1,9,0,101,0,9,-1,0.0,0.0,0.0,0.0,0.0,4.0

It's usually a good idea to back up large tables of extracted / wrangled features before you join them onto another one, that way you can go back to it easily if you need to make changes to it.

In [0]:
df.to_pickle(f'{DATA_PATH}df.pkl')

In [0]:
df = pd.read_pickle(f'{DATA_PATH}df.pkl')

In [0]:
df.head()

,Date,Store,AfterSchoolHoliday,BeforeSchoolHoliday,AfterStateHoliday,BeforeStateHoliday,AfterPromo,BeforePromo,SchoolHoliday_bw,StateHoliday_bw,Promo_bw,SchoolHoliday_fw,StateHoliday_fw,Promo_fw
0,2015-09-17,1,13,0,105,0,0,0,0.0,0.0,4.0,0.0,0.0,1.0
1,2015-09-16,1,12,0,104,0,0,0,0.0,0.0,3.0,0.0,0.0,2.0
2,2015-09-15,1,11,0,103,0,0,0,0.0,0.0,2.0,0.0,0.0,3.0
3,2015-09-14,1,10,0,102,0,0,0,0.0,0.0,1.0,0.0,0.0,4.0
4,2015-09-13,1,9,0,101,0,9,-1,0.0,0.0,0.0,0.0,0.0,4.0

In [0]:
df["Date"] = pd.to_datetime(df.Date)

In [0]:
df.columns

Index(['Date', 'Store', 'AfterSchoolHoliday', 'BeforeSchoolHoliday',
       'AfterStateHoliday', 'BeforeStateHoliday', 'AfterPromo', 'BeforePromo',
       'SchoolHoliday_bw', 'StateHoliday_bw', 'Promo_bw', 'SchoolHoliday_fw',
       'StateHoliday_fw', 'Promo_fw'],
      dtype='object')

In [0]:
joined = join_df(joined, df, ['Store', 'Date'])

In [0]:
joined_test = join_df(joined_test, df, ['Store', 'Date'])

In [0]:
joined = joined[joined.Sales!=0]

In [0]:
joined.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,Year,...,AfterStateHoliday,BeforeStateHoliday,AfterPromo,BeforePromo,SchoolHoliday_bw,StateHoliday_bw,Promo_bw,SchoolHoliday_fw,StateHoliday_fw,Promo_fw
0,1,5,2015-07-31,5263,555,1,1,False,1,2015,...,57,0,0,0,5.0,0.0,5.0,7.0,0.0,5.0
1,2,5,2015-07-31,6064,625,1,1,False,1,2015,...,67,0,0,0,5.0,0.0,5.0,1.0,0.0,1.0
2,3,5,2015-07-31,8314,821,1,1,False,1,2015,...,57,0,0,0,5.0,0.0,5.0,5.0,0.0,5.0
3,4,5,2015-07-31,13995,1498,1,1,False,1,2015,...,67,0,0,0,5.0,0.0,5.0,1.0,0.0,1.0
4,5,5,2015-07-31,4822,559,1,1,False,1,2015,...,57,0,0,0,5.0,0.0,5.0,1.0,0.0,1.0

In [0]:
joined.reset_index(inplace=True)
joined_test.reset_index(inplace=True)

In [0]:
joined.to_pickle(f'{DATA_PATH}joined.pkl')
joined_test.to_pickle(f'{DATA_PATH}joined_test.pkl')

We now have our final set of engineered features.

While these steps were explicitly outlined in the paper, these are all fairly typical feature engineering steps for dealing with time series data and are practical in any similar setting.

## Create features

In [0]:
joined = pd.read_pickle(os.path.join(DATA_PATH, 'joined.pkl'))
joined_test = pd.read_pickle(os.path.join(DATA_PATH, 'joined_test.pkl'))

In [72]:
joined.head().T.head(40)

,0,1,2,3,4
index,0,1,2,3,4
Store,1,2,3,4,5
DayOfWeek,5,5,5,5,5
Date,2015-07-31 00:00:00,2015-07-31 00:00:00,2015-07-31 00:00:00,2015-07-31 00:00:00,2015-07-31 00:00:00
Sales,5263,6064,8314,13995,4822
Customers,555,625,821,1498,559
Open,1,1,1,1,1
Promo,1,1,1,1,1
StateHoliday,False,False,False,False,False
SchoolHoliday,1,1,1,1,1
Year,2015,2015,2015,2015,2015
Month,7,7,7,7,7
Week,31,31,31,31,31
Day,31,31,31,31,31
Dayofweek,4,4,4,4,4
Dayofyear,212,212,212,212,212
Is_month_end,True,True,True,True,True
Is_month_start,False,False,False,False,False
Is_quarter_end,False,False,False,False,False
Is_quarter_start,False,False,False,False,False
Is_year_end,False,False,False,False,False
Is_year_start,False,False,False,False,False
Elapsed,1438300800,1438300800,1438300800,1438300800,1438300800
StoreType,c,a,a,c,a
Assortment,a,a,a,c,a
CompetitionDistance,1270,570,14130,620,29910
CompetitionOpenSinceMonth,9,11,12,9,4
CompetitionOpenSinceYear,2008,2007,2006,2009,2015
Promo2,0,1,1,0,0
Promo2SinceWeek,1,13,14,1,1
Promo2SinceYear,1900,2010,2011,1900,1900
PromoInterval,NaN,"Jan,Apr,Jul,Oct","Jan,Apr,Jul,Oct",NaN,NaN
State,HE,TH,NW,BE,SN
file,Rossmann_DE_HE,Rossmann_DE_TH,Rossmann_DE_NW,Rossmann_DE_BE,Rossmann_DE_SN
week,2015-08-02 - 2015-08-08,2015-08-02 - 2015-08-08,2015-08-02 - 2015-08-08,2015-08-02 - 2015-08-08,2015-08-02 - 2015-08-08
trend,85,80,86,74,82
file_DE,Rossmann_DE,Rossmann_DE,Rossmann_DE,Rossmann_DE,Rossmann_DE
week_DE,2015-08-02 - 2015-08-08,2015-08-02 - 2015-08-08,2015-08-02 - 2015-08-08,2015-08-02 - 2015-08-08,2015-08-02 - 2015-08-08
trend_DE,83,83,83,83,83
Date_DE,2015-08-02 00:00:00,2015-08-02 00:00:00,2015-08-02 00:00:00,2015-08-02 00:00:00,2015-08-02 00:00:00

Now that we've engineered all our features, we need to convert to input compatible with a neural network.

This includes converting categorical variables into contiguous integers or one-hot encodings, normalizing continuous features to standard normal, etc...

In [73]:
cat_vars = ['Store', 'DayOfWeek', 'Year', 'Month', 'Day', 'StateHoliday', 'CompetitionMonthsOpen',
    'Promo2Weeks', 'StoreType', 'Assortment', 'PromoInterval', 'CompetitionOpenSinceYear', 'Promo2SinceYear',
    'State', 'Week', 'Events', 'Promo_fw', 'Promo_bw', 'StateHoliday_fw', 'StateHoliday_bw',
    'SchoolHoliday_fw', 'SchoolHoliday_bw']

contin_vars = ['CompetitionDistance', 'Max_TemperatureC', 'Mean_TemperatureC', 'Min_TemperatureC',
   'Max_Humidity', 'Mean_Humidity', 'Min_Humidity', 'Max_Wind_SpeedKm_h', 
   'Mean_Wind_SpeedKm_h', 'CloudCover', 'trend', 'trend_DE',
   'AfterStateHoliday', 'BeforeStateHoliday', 'Promo', 'SchoolHoliday']

n = len(joined); n

844338

In [0]:
dep = 'Sales'
joined = joined[cat_vars+contin_vars+[dep, 'Date']].copy()

In [0]:
joined_test[dep] = 0
joined_test = joined_test[cat_vars+contin_vars+[dep, 'Date', 'Id']].copy()

In [0]:
for v in cat_vars: joined[v] = joined[v].astype('category').cat.as_ordered()

In [0]:
def apply_cats(df, trn):
    """Changes any columns of strings in df into categorical variables using trn as
    a template for the category codes.

    Parameters:
    -----------
    df: A pandas dataframe. Any columns of strings will be changed to
        categorical values. The category codes are determined by trn.

    trn: A pandas dataframe. When creating a category for df, it looks up the
        what the category's code were in trn and makes those the category codes
        for df.

    """
    for n,c in df.items():
        if (n in trn.columns) and (trn[n].dtype.name=='category'):
            df[n] = pd.Categorical(c, categories=trn[n].cat.categories, ordered=True)

In [0]:
apply_cats(joined_test, joined)

In [0]:
for v in contin_vars:
    joined[v] = joined[v].fillna(0).astype('float32')
    joined_test[v] = joined_test[v].fillna(0).astype('float32')

We can now process our data

In [0]:
def fix_missing(df, col, name, na_dict):
    """ Fill missing data in a column of df with the median, and add a {name}_na column
    which specifies if the data was missing.

    Parameters:
    -----------
    df: The data frame that will be changed.

    col: The column of data to fix by filling in missing data.

    name: The name of the new filled column in df.

    na_dict: A dictionary of values to create na's of and the value to insert. If
        name is not a key of na_dict the median will fill any missing data. Also
        if name is not a key of na_dict and there is no missing data in col, then
        no {name}_na column is not created.


    Examples:
    ---------
    >>> df = pd.DataFrame({'col1' : [1, np.NaN, 3], 'col2' : [5, 2, 2]})
    >>> df
       col1 col2
    0     1    5
    1   nan    2
    2     3    2

    >>> fix_missing(df, df['col1'], 'col1', {})
    >>> df
       col1 col2 col1_na
    0     1    5   False
    1     2    2    True
    2     3    2   False


    >>> df = pd.DataFrame({'col1' : [1, np.NaN, 3], 'col2' : [5, 2, 2]})
    >>> df
       col1 col2
    0     1    5
    1   nan    2
    2     3    2

    >>> fix_missing(df, df['col2'], 'col2', {})
    >>> df
       col1 col2
    0     1    5
    1   nan    2
    2     3    2


    >>> df = pd.DataFrame({'col1' : [1, np.NaN, 3], 'col2' : [5, 2, 2]})
    >>> df
       col1 col2
    0     1    5
    1   nan    2
    2     3    2

    >>> fix_missing(df, df['col1'], 'col1', {'col1' : 500})
    >>> df
       col1 col2 col1_na
    0     1    5   False
    1   500    2    True
    2     3    2   False
    """
    if is_numeric_dtype(col):
        if pd.isnull(col).sum() or (name in na_dict):
            df[name+'_na'] = pd.isnull(col)
            filler = na_dict[name] if name in na_dict else col.median()
            df[name] = col.fillna(filler)
            na_dict[name] = filler
    return na_dict

def numericalize(df, col, name, max_n_cat):
    """ Changes the column col from a categorical type to it's integer codes.

    Parameters:
    -----------
    df: A pandas dataframe. df[name] will be filled with the integer codes from
        col.

    col: The column you wish to change into the categories.
    name: The column name you wish to insert into df. This column will hold the
        integer codes.

    max_n_cat: If col has more categories than max_n_cat it will not change the
        it to its integer codes. If max_n_cat is None, then col will always be
        converted.

    Examples:
    ---------
    >>> df = pd.DataFrame({'col1' : [1, 2, 3], 'col2' : ['a', 'b', 'a']})
    >>> df
       col1 col2
    0     1    a
    1     2    b
    2     3    a

    note the type of col2 is string

    >>> train_cats(df)
    >>> df

       col1 col2
    0     1    a
    1     2    b
    2     3    a

    now the type of col2 is category { a : 1, b : 2}

    >>> numericalize(df, df['col2'], 'col3', None)

       col1 col2 col3
    0     1    a    1
    1     2    b    2
    2     3    a    1
    """
    if not is_numeric_dtype(col) and ( max_n_cat is None or len(col.cat.categories)>max_n_cat):
        df[name] = col.cat.codes+1

def scale_vars(df, mapper):
    warnings.filterwarnings('ignore', category=sklearn.exceptions.DataConversionWarning)
    if mapper is None:
        map_f = [([n],StandardScaler()) for n in df.columns if is_numeric_dtype(df[n])]
        mapper = DataFrameMapper(map_f).fit(df)
    df[mapper.transformed_names_] = mapper.transform(df)
    return mapper        
        

def proc_df(df, y_fld=None, skip_flds=None, ignore_flds=None, do_scale=False, na_dict=None,
            preproc_fn=None, max_n_cat=None, subset=None, mapper=None):
    """ proc_df takes a data frame df and splits off the response variable, and
    changes the df into an entirely numeric dataframe. For each column of df 
    which is not in skip_flds nor in ignore_flds, na values are replaced by the
    median value of the column.

    Parameters:
    -----------
    df: The data frame you wish to process.

    y_fld: The name of the response variable

    skip_flds: A list of fields that dropped from df.

    ignore_flds: A list of fields that are ignored during processing.

    do_scale: Standardizes each column in df. Takes Boolean Values(True,False)

    na_dict: a dictionary of na columns to add. Na columns are also added if there
        are any missing values.

    preproc_fn: A function that gets applied to df.

    max_n_cat: The maximum number of categories to break into dummy values, instead
        of integer codes.

    subset: Takes a random subset of size subset from df.

    mapper: If do_scale is set as True, the mapper variable
        calculates the values used for scaling of variables during training time (mean and standard deviation).

    Returns:
    --------
    [x, y, nas, mapper(optional)]:

        x: x is the transformed version of df. x will not have the response variable
            and is entirely numeric.

        y: y is the response variable

        nas: returns a dictionary of which nas it created, and the associated median.

        mapper: A DataFrameMapper which stores the mean and standard deviation of the corresponding continuous
        variables which is then used for scaling of during test-time.

    Examples:
    ---------
    >>> df = pd.DataFrame({'col1' : [1, 2, 3], 'col2' : ['a', 'b', 'a']})
    >>> df
       col1 col2
    0     1    a
    1     2    b
    2     3    a

    note the type of col2 is string

    >>> train_cats(df)
    >>> df

       col1 col2
    0     1    a
    1     2    b
    2     3    a

    now the type of col2 is category { a : 1, b : 2}

    >>> x, y, nas = proc_df(df, 'col1')
    >>> x

       col2
    0     1
    1     2
    2     1

    >>> data = DataFrame(pet=["cat", "dog", "dog", "fish", "cat", "dog", "cat", "fish"],
                 children=[4., 6, 3, 3, 2, 3, 5, 4],
                 salary=[90, 24, 44, 27, 32, 59, 36, 27])

    >>> mapper = DataFrameMapper([(:pet, LabelBinarizer()),
                          ([:children], StandardScaler())])

    >>>round(fit_transform!(mapper, copy(data)), 2)

    8x4 Array{Float64,2}:
    1.0  0.0  0.0   0.21
    0.0  1.0  0.0   1.88
    0.0  1.0  0.0  -0.63
    0.0  0.0  1.0  -0.63
    1.0  0.0  0.0  -1.46
    0.0  1.0  0.0  -0.63
    1.0  0.0  0.0   1.04
    0.0  0.0  1.0   0.21
    """
    if not ignore_flds: ignore_flds=[]
    if not skip_flds: skip_flds=[]
    if subset: df = get_sample(df,subset)
    else: df = df.copy()
    ignored_flds = df.loc[:, ignore_flds]
    df.drop(ignore_flds, axis=1, inplace=True)
    if preproc_fn: preproc_fn(df)
    if y_fld is None: y = None
    else:
        if not is_numeric_dtype(df[y_fld]): df[y_fld] = df[y_fld].cat.codes
        y = df[y_fld].values
        skip_flds += [y_fld]
    df.drop(skip_flds, axis=1, inplace=True)

    if na_dict is None: na_dict = {}
    else: na_dict = na_dict.copy()
    na_dict_initial = na_dict.copy()
    for n,c in df.items(): na_dict = fix_missing(df, c, n, na_dict)
    if len(na_dict_initial.keys()) > 0:
        df.drop([a + '_na' for a in list(set(na_dict.keys()) - set(na_dict_initial.keys()))], axis=1, inplace=True)
    if do_scale: mapper = scale_vars(df, mapper)
    for n,c in df.items(): numericalize(df, c, n, max_n_cat)
    df = pd.get_dummies(df, dummy_na=True)
    df = pd.concat([ignored_flds, df], axis=1)
    res = [df, y, na_dict]
    if do_scale: res = res + [mapper]
    return res

In [0]:
joined = joined.set_index("Date")

In [0]:
df_train, y, nas, mapper = proc_df(joined, 'Sales', do_scale=True)

Transform response variable to scaled log

In [0]:
max_y_log = max(np.log(y))

def yl_for_fit(y):
    return np.log(y) / max_y_log

def inv_yl_for_pred(yl):
    return np.exp(yl * max_y_log)

In [0]:
yl = yl_for_fit(y)

In [0]:
joined_test = joined_test.set_index("Date")

In [0]:
df_test, _, nas, mapper = proc_df(joined_test, 'Sales', do_scale=True, skip_flds=['Id'],
                                  mapper=mapper, na_dict=nas)

In [97]:
df_train.head(2)

,Store,DayOfWeek,Year,Month,Day,StateHoliday,CompetitionMonthsOpen,Promo2Weeks,StoreType,Assortment,...,Min_Humidity,Max_Wind_SpeedKm_h,Mean_Wind_SpeedKm_h,CloudCover,trend,trend_DE,AfterStateHoliday,BeforeStateHoliday,Promo,SchoolHoliday
Date,,,,,,,,,,,,,,,,,,,,,
2015-07-31,1,5,3,7,31,1,25,1,3,1,...,-1.620066,0.149027,-0.142774,-1.844823,1.732493,1.724336,0.604460,1.13112,1.113717,2.04105
2015-07-31,2,5,3,7,31,1,25,26,1,1,...,-1.264031,-0.960613,-0.142774,-0.488722,1.294579,1.724336,0.926957,1.13112,1.113717,2.04105

In [0]:
#df_train.to_pickle(os.path.join(DATA_PATH, 'df_train.pkl'))
#df_test.to_pickle(os.path.join(DATA_PATH, 'df_test.pkl'))

In [0]:
df_train = pd.read_pickle(os.path.join(DATA_PATH, 'df_train.pkl'))
df_test = pd.read_pickle(os.path.join(DATA_PATH, 'df_test.pkl'))

### Validation set

Good approach to take __validation set__ is using the exact same length of time period as the test set uses - this is implemented here:

In [0]:
val_idx = np.flatnonzero(
    (df_train.index<=pd.datetime(2014,9,17)) & (df_train.index>=pd.datetime(2014,8,1)))

In [0]:
all_idx = np.flatnonzero(df_train.index)

In [0]:
trn_idx = np.setdiff1d(all_idx, val_idx)

In [0]:
def split_by_idx(val_idx, df, y):
    
    """
        Parameters:
    -----------
    df: The data frame with data to split on train and validation set.

    y_fld: The numpy array with target values 

    Returns:
    --------
    [trn, val, y_trn, y_val]:

        Analogical to sklearn.model_selection.train_test_split function.
        Outputs are in the same format as inputs.
        
    """
    all_idx = np.flatnonzero(df.index)
    trn_idx = np.setdiff1d(all_idx, val_idx)
    
    trn = df.iloc[trn_idx]
    val = df.iloc[val_idx]
    
    _srs_y = pd.Series(data=y, index=df.index)
    
    y_trn = np.array(_srs_y[trn_idx])
    y_val = np.array(_srs_y[val_idx])
    
    return trn, val, y_trn, y_val

In [0]:
trn, val, yl_trn, yl_val = split_by_idx(val_idx, df_train, yl)

## Fast-check model

We're ready to put together our models.

Root-mean-squared percent error is the metric Kaggle used for this competition.

In [0]:
def exp_rmspe(y_pred, targ):
    targ = inv_yl_for_pred(targ)
    pct_var = (targ - inv_yl_for_pred(y_pred))/targ
    return math.sqrt((pct_var**2).mean())

In [0]:
from sklearn.ensemble import RandomForestRegressor

In [0]:
rf = RandomForestRegressor(n_estimators=40, max_features=0.99, min_samples_leaf=2,
                          n_jobs=-1, oob_score=True)

In [123]:
rf.fit(trn, yl_trn)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features=0.99, max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=2, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=40, n_jobs=-1,
           oob_score=True, random_state=None, verbose=0, warm_start=False)

In [0]:
pred_val = rf.predict(val)

In [125]:
rf.score(trn, yl_trn), rf.score(val, yl_val), rf.oob_score_, exp_rmspe(pred_val, yl_val)

(0.9823453086095262,
 0.9307745924936762,
 0.9249201067237659,
 0.10961259334130233)

In [0]:
## Test kaggle Score
pred_test_l = rf.predict(df_test)
pred_test = inv_yl_for_pred(pred_test_l)

In [0]:
def generate_sub_file(pred, sub_name):
  
  sub = joined_test[['Id']]
  sub.loc[:, 'Sales'] = pred
  sub.to_csv(os.path.join(HOME_PATH, 'submitions',(f'{sub_name}' + '.csv')), index=False)

In [0]:
commition = joined_test[['Id']]

In [137]:
commition.head()

            Id        Sales
Date
2015-09-17   1  4902.982294
2015-09-17   2  8449.929772
2015-09-17   3  9458.724531
2015-09-17   4  6854.191918
2015-09-17   5  7649.186649

In [0]:
commition.loc[:, 'Sales'] = pred_test

In [0]:
commition.to_csv(os.path.join(DATA_PATH, 'sub.csv'), index=False)

Test kaggle score: 0.127

## Embeddings

In [0]:
cat_sz = [(c, len(joined[c].cat.categories) + 1) for c in cat_vars]

In [34]:
cat_sz

[('Store', 1116),
 ('DayOfWeek', 8),
 ('Year', 4),
 ('Month', 13),
 ('Day', 32),
 ('StateHoliday', 3),
 ('CompetitionMonthsOpen', 26),
 ('Promo2Weeks', 27),
 ('StoreType', 5),
 ('Assortment', 4),
 ('PromoInterval', 4),
 ('CompetitionOpenSinceYear', 24),
 ('Promo2SinceYear', 9),
 ('State', 13),
 ('Week', 53),
 ('Events', 22),
 ('Promo_fw', 7),
 ('Promo_bw', 7),
 ('StateHoliday_fw', 4),
 ('StateHoliday_bw', 4),
 ('SchoolHoliday_fw', 9),
 ('SchoolHoliday_bw', 9)]

We use the *cardinality* of each variable (that is, its number of unique values) to decide how large to make its *embeddings*. Each level will be associated with a vector with length defined as below.

In [0]:
emb_szs = [(c, min(50, (c+1)//2)) for _,c in cat_sz]

In [37]:
emb_szs

[(1116, 50),
 (8, 4),
 (4, 2),
 (13, 7),
 (32, 16),
 (3, 2),
 (26, 13),
 (27, 14),
 (5, 3),
 (4, 2),
 (4, 2),
 (24, 12),
 (9, 5),
 (13, 7),
 (53, 27),
 (22, 11),
 (7, 4),
 (7, 4),
 (4, 2),
 (4, 2),
 (9, 5),
 (9, 5)]

In [0]:
from keras.models import Sequential, Model
from keras.layers import Input, Dense, Concatenate, Embedding, Reshape, Dropout

Example how embeddings are constructed for one variable `DayOfWeek`

In [0]:
# 'DayOfWeek'
no_of_unique_cat = emb_szs[1][0]
embedding_size = emb_szs[1][1]


model = Sequential()
model.add(Embedding(input_dim=no_of_unique_cat, output_dim=embedding_size, input_length=1))
model.add(Reshape(target_shape=(embedding_size,)))
model.compile('rmsprop', 'mse')

In [0]:
input_dayofweek = df['DayOfWeek'].values

In [40]:
input_dayofweek.shape

(844338,)

In [0]:
model.fit(input_dayofweek, yl, epochs=3, batch_size=128)

In [0]:
output_dayofweek = model.predict(input_dayofweek)

In [44]:
output_dayofweek.shape

(844338, 4)

In [46]:
output_dayofweek[0]

array([-0.02567384, -0.04963464,  0.03044173,  0.04538769], dtype=float32)

Now each categorical variable (here: day of week) is represented by vector of length 4

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 844338 entries, 2015-07-31 to 2013-01-01
Data columns (total 38 columns):
Store                       844338 non-null int16
DayOfWeek                   844338 non-null int8
Year                        844338 non-null int8
Month                       844338 non-null int8
Day                         844338 non-null int8
StateHoliday                844338 non-null int8
CompetitionMonthsOpen       844338 non-null int8
Promo2Weeks                 844338 non-null int8
StoreType                   844338 non-null int8
Assortment                  844338 non-null int8
PromoInterval               844338 non-null int8
CompetitionOpenSinceYear    844338 non-null int8
Promo2SinceYear             844338 non-null int8
State                       844338 non-null int8
Week                        844338 non-null int8
Events                      844338 non-null int8
Promo_fw                    844338 non-null int8
Promo_bw                    844338 non-null int8
StateHoliday_fw             844338 non-null int8
StateHoliday_bw             844338 non-null int8
SchoolHoliday_fw            844338 non-null int8
SchoolHoliday_bw            844338 non-null int8
CompetitionDistance         844338 non-null float64
Max_TemperatureC            844338 non-null float64
Mean_TemperatureC           844338 non-null float64
Min_TemperatureC            844338 non-null float64
Max_Humidity                844338 non-null float64
Mean_Humidity               844338 non-null float64
Min_Humidity                844338 non-null float64
Max_Wind_SpeedKm_h          844338 non-null float64
Mean_Wind_SpeedKm_h         844338 non-null float64
CloudCover                  844338 non-null float64
trend                       844338 non-null float64
trend_DE                    844338 non-null float64
AfterStateHoliday           844338 non-null float64
BeforeStateHoliday          844338 non-null float64
Promo                       844338 non-null float64
SchoolHoliday               844338 non-null float64
dtypes: float64(16), int16(1), int8(21)
memory usage: 148.0 MB

In [0]:
def build_embedding_network(emb_szs):


    inputs = []
    embeddings = []

    for nam_unique_cat, emb_sz in emb_szs:
      
        input_shape = Input(shape=(1,))
        embedding = Embedding(nam_unique_cat, emb_sz, input_length=1)(input_shape)
        embedding = Reshape(target_shape=(emb_sz,))(embedding)
        inputs.append(input_shape)
        embeddings.append(embedding)
        
        
        

    input_distance = Input(shape=(1,))
    embedding_numeric = Dense(1)(input_distance) 
    inputs.append(input_distance)
    embeddings.append(embedding_numeric)

    input_temperature = Input(shape=(3,))
    embedding_numeric = Dense(3)(input_temperature) 
    inputs.append(input_temperature)
    embeddings.append(embedding_numeric)    

    input_humidity = Input(shape=(3,))
    embedding_numeric = Dense(3)(input_humidity) 
    inputs.append(input_humidity)
    embeddings.append(embedding_numeric)  

    input_wind = Input(shape=(2,))
    embedding_numeric = Dense(2)(input_wind) 
    inputs.append(input_wind)
    embeddings.append(embedding_numeric)     

    input_cloud = Input(shape=(1,))
    embedding_numeric = Dense(1)(input_cloud) 
    inputs.append(input_cloud)
    embeddings.append(embedding_numeric)     

    input_trend = Input(shape=(1,))
    embedding_numeric = Dense(1)(input_trend) 
    inputs.append(input_trend)
    embeddings.append(embedding_numeric)      


    input_trend_de = Input(shape=(1,))
    embedding_numeric = Dense(1)(input_trend_de) 
    inputs.append(input_trend_de)
    embeddings.append(embedding_numeric)     

    input_afterstateholiday  = Input(shape=(1,))
    embedding_numeric = Dense(1)(input_afterstateholiday) 
    inputs.append(input_afterstateholiday)
    embeddings.append(embedding_numeric)

    input_beforestateholiday  = Input(shape=(1,))
    embedding_numeric = Dense(1)(input_beforestateholiday) 
    inputs.append(input_beforestateholiday)
    embeddings.append(embedding_numeric)        

    input_promo  = Input(shape=(1,))
    embedding_numeric = Dense(1)(input_promo) 
    inputs.append(input_promo)
    embeddings.append(embedding_numeric)   

    input_schoolholiday  = Input(shape=(1,))
    embedding_numeric = Dense(1)(input_schoolholiday) 
    inputs.append(input_schoolholiday)
    embeddings.append(embedding_numeric)   
        
        
    x = Concatenate()(embeddings)
    x = Dropout(0.02)(x)
    x = Dense(1000, activation='relu', 
              kernel_initializer='random_uniform', bias_initializer='random_uniform')(x)
    x = Dense(500, activation='relu', 
              kernel_initializer='random_uniform', bias_initializer='random_uniform')(x)
    output = Dense(1, activation='sigmoid')(x)
    
    model = Model(inputs, output)
    model.compile(loss='mean_absolute_error', optimizer='adam')

    return model

In [0]:
def convert_df_to_nn_format(df):
  
    res = []
    # categorical vars of shape=(1,)
    for c in df.columns:
      if len(res) < 22:
        res.append(df[c].values)
    
    
    # input_distance
    res.append(df.iloc[:, 22].values)
    # input_temperature
    res.append(df.iloc[:, 23:26].values)    
    # input_humidity
    res.append(df.iloc[:, 26:29].values)      
    # input_wind
    res.append(df.iloc[:, 29:31].values)   
    # input_cloud
    res.append(df.iloc[:, 31].values) 
    # input_trend
    res.append(df.iloc[:, 32].values) 
    # input_trend_de
    res.append(df.iloc[:, 33].values) 
    # input_afterstateholiday
    res.append(df.iloc[:, 34].values) 
    # input_beforestateholiday
    res.append(df.iloc[:, 35].values)   
    # input_promo
    res.append(df.iloc[:, 36].values)     
    # input_schoolholiday
    res.append(df.iloc[:, 37].values)   
            
    return res

In [0]:
NN = build_embedding_network(emb_szs)

In [184]:
NN.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_556 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_557 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_558 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_559 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_560 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_561 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_562 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_563 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_564 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_565 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_566 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_567 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_568 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_569 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_570 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_571 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_572 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_573 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_574 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_575 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_576 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_577 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
embedding_70 (Embedding)        (None, 1, 50)        55800       input_556[0][0]
__________________________________________________________________________________________________
embedding_71 (Embedding)        (None, 1, 4)         32          input_557[0][0]
__________________________________________________________________________________________________
embedding_72 (Embedding)        (None, 1, 2)         8           input_558[0][0]
__________________________________________________________________________________________________
embedding_73 (Embedding)        (None, 1, 7)         91          input_559[0][0]
__________________________________________________________________________________________________
embedding_74 (Embedding)        (None, 1, 16)        512         input_560[0][0]
__________________________________________________________________________________________________
embedding_75 (Embedding)        (None, 1, 2)         6           input_561[0][0]
__________________________________________________________________________________________________
embedding_76 (Embedding)        (None, 1, 13)        338         input_562[0][0]
__________________________________________________________________________________________________
embedding_77 (Embedding)        (None, 1, 14)        378         input_563[0][0]
__________________________________________________________________________________________________
embedding_78 (Embedding)        (None, 1, 3)         15          input_564[0][0]
__________________________________________________________________________________________________
embedding_79 (Embedding)        (None, 1, 2)         8           input_565[0][0]
__________________________________________________________________________________________________
embedding_80 (Embedding)        (None, 1, 2)         8           input_566[0][0]
__________________________________________________________________________________________________
embedding_81 (Embedding)        (None, 1, 12)        288         input_567[0][0]
__________________________________________________________________________________________________
embedding_82 (Embedding)        (None, 1, 5)         45          input_568[0][0]
__________________________________________________________________________________________________
embedding_83 (Embedding)        (None, 1, 7)         91          input_569[0][0]
__________________________________________________________________________________________________
embedding_84 (Embedding)        (None, 1, 27)        1431        input_570[0][0]
__________________________________________________________________________________________________
embedding_85 (Embedding)        (None, 1, 11)        242         input_571[0][0]
__________________________________________________________________________________________________
embedding_86 (Embedding)        (None, 1, 4)         28          input_572[0][0]
__________________________________________________________________________________________________
embedding_87 (Embedding)        (None, 1, 4)         28          input_573[0][0]
__________________________________________________________________________________________________
embedding_88 (Embedding)        (None, 1, 2)         8           input_574[0][0]
__________________________________________________________________________________________________
embedding_89 (Embedding)        (None, 1, 2)         8           input_575[0][0]
__________________________________________________________________________________________________
embedding_90 (Embedding)        (None, 1, 5)         45          input_576[0][0]
__________________________________________________________________________________________________
embedding_91 (Embedding)        (None, 1, 5)         45          input_577[0][0]
__________________________________________________________________________________________________
input_578 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_579 (InputLayer)          (None, 3)            0
__________________________________________________________________________________________________
input_580 (InputLayer)          (None, 3)            0
__________________________________________________________________________________________________
input_581 (InputLayer)          (None, 2)            0
__________________________________________________________________________________________________
input_582 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_583 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_584 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_585 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_586 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_587 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
input_588 (InputLayer)          (None, 1)            0
__________________________________________________________________________________________________
reshape_70 (Reshape)            (None, 50)           0           embedding_70[0][0]
__________________________________________________________________________________________________
reshape_71 (Reshape)            (None, 4)            0           embedding_71[0][0]
__________________________________________________________________________________________________
reshape_72 (Reshape)            (None, 2)            0           embedding_72[0][0]
__________________________________________________________________________________________________
reshape_73 (Reshape)            (None, 7)            0           embedding_73[0][0]
__________________________________________________________________________________________________
reshape_74 (Reshape)            (None, 16)           0           embedding_74[0][0]
__________________________________________________________________________________________________
reshape_75 (Reshape)            (None, 2)            0           embedding_75[0][0]
__________________________________________________________________________________________________
reshape_76 (Reshape)            (None, 13)           0           embedding_76[0][0]
__________________________________________________________________________________________________
reshape_77 (Reshape)            (None, 14)           0           embedding_77[0][0]
__________________________________________________________________________________________________
reshape_78 (Reshape)            (None, 3)            0           embedding_78[0][0]
__________________________________________________________________________________________________
reshape_79 (Reshape)            (None, 2)            0           embedding_79[0][0]
__________________________________________________________________________________________________
reshape_80 (Reshape)            (None, 2)            0           embedding_80[0][0]
__________________________________________________________________________________________________
reshape_81 (Reshape)            (None, 12)           0           embedding_81[0][0]
__________________________________________________________________________________________________
reshape_82 (Reshape)            (None, 5)            0           embedding_82[0][0]
__________________________________________________________________________________________________
reshape_83 (Reshape)            (None, 7)            0           embedding_83[0][0]
__________________________________________________________________________________________________
reshape_84 (Reshape)            (None, 27)           0           embedding_84[0][0]
__________________________________________________________________________________________________
reshape_85 (Reshape)            (None, 11)           0           embedding_85[0][0]
__________________________________________________________________________________________________
reshape_86 (Reshape)            (None, 4)            0           embedding_86[0][0]
__________________________________________________________________________________________________
reshape_87 (Reshape)            (None, 4)            0           embedding_87[0][0]
__________________________________________________________________________________________________
reshape_88 (Reshape)            (None, 2)            0           embedding_88[0][0]
__________________________________________________________________________________________________
reshape_89 (Reshape)            (None, 2)            0           embedding_89[0][0]
__________________________________________________________________________________________________
reshape_90 (Reshape)            (None, 5)            0           embedding_90[0][0]
__________________________________________________________________________________________________
reshape_91 (Reshape)            (None, 5)            0           embedding_91[0][0]
__________________________________________________________________________________________________
dense_499 (Dense)               (None, 1)            2           input_578[0][0]
__________________________________________________________________________________________________
dense_500 (Dense)               (None, 3)            12          input_579[0][0]
__________________________________________________________________________________________________
dense_501 (Dense)               (None, 3)            12          input_580[0][0]
__________________________________________________________________________________________________
dense_502 (Dense)               (None, 2)            6           input_581[0][0]
__________________________________________________________________________________________________
dense_503 (Dense)               (None, 1)            2           input_582[0][0]
__________________________________________________________________________________________________
dense_504 (Dense)               (None, 1)            2           input_583[0][0]
__________________________________________________________________________________________________
dense_505 (Dense)               (None, 1)            2           input_584[0][0]
__________________________________________________________________________________________________
dense_506 (Dense)               (None, 1)            2           input_585[0][0]
__________________________________________________________________________________________________
dense_507 (Dense)               (None, 1)            2           input_586[0][0]
__________________________________________________________________________________________________
dense_508 (Dense)               (None, 1)            2           input_587[0][0]
__________________________________________________________________________________________________
dense_509 (Dense)               (None, 1)            2           input_588[0][0]
__________________________________________________________________________________________________
concatenate_5 (Concatenate)     (None, 215)          0           reshape_70[0][0]
                                                                 reshape_71[0][0]
                                                                 reshape_72[0][0]
                                                                 reshape_73[0][0]
                                                                 reshape_74[0][0]
                                                                 reshape_75[0][0]
                                                                 reshape_76[0][0]
                                                                 reshape_77[0][0]
                                                                 reshape_78[0][0]
                                                                 reshape_79[0][0]
                                                                 reshape_80[0][0]
                                                                 reshape_81[0][0]
                                                                 reshape_82[0][0]
                                                                 reshape_83[0][0]
                                                                 reshape_84[0][0]
                                                                 reshape_85[0][0]
                                                                 reshape_86[0][0]
                                                                 reshape_87[0][0]
                                                                 reshape_88[0][0]
                                                                 reshape_89[0][0]
                                                                 reshape_90[0][0]
                                                                 reshape_91[0][0]
                                                                 dense_499[0][0]
                                                                 dense_500[0][0]
                                                                 dense_501[0][0]
                                                                 dense_502[0][0]
                                                                 dense_503[0][0]
                                                                 dense_504[0][0]
                                                                 dense_505[0][0]
                                                                 dense_506[0][0]
                                                                 dense_507[0][0]
                                                                 dense_508[0][0]
                                                                 dense_509[0][0]
__________________________________________________________________________________________________
dropout_4 (Dropout)             (None, 215)          0           concatenate_5[0][0]
__________________________________________________________________________________________________
dense_510 (Dense)               (None, 1000)         216000      dropout_4[0][0]
__________________________________________________________________________________________________
dense_511 (Dense)               (None, 500)          500500      dense_510[0][0]
__________________________________________________________________________________________________
dense_512 (Dense)               (None, 1)            501         dense_511[0][0]
==================================================================================================
Total params: 776,502
Trainable params: 776,502
Non-trainable params: 0
__________________________________________________________________________________________________

In [0]:
def save_model(model, model_name):
    model.save(os.path.join(HOME_PATH, 'models',(f'{model_name}' + '.h5')))
    
def load_model(model_name):
    return models.load_model(os.path.join(HOME_PATH, 'models',(f'{model_name}' + '.h5')))

In [0]:
list_train = convert_df_to_nn_format(df_train)

In [186]:
len(list_train)

33

In [187]:
NN.fit(list_train, yl, epochs=20, batch_size=128)

Epoch 1/20
844338/844338 [==============================] - 184s 218us/step - loss: 0.0098
Epoch 2/20
844338/844338 [==============================] - 179s 212us/step - loss: 0.0073
Epoch 3/20
844338/844338 [==============================] - 178s 211us/step - loss: 0.0069
Epoch 4/20
844338/844338 [==============================] - 179s 212us/step - loss: 0.0066
Epoch 5/20
844338/844338 [==============================] - 178s 211us/step - loss: 0.0064
Epoch 6/20
844338/844338 [==============================] - 179s 212us/step - loss: 0.0062
Epoch 7/20
844338/844338 [==============================] - 179s 212us/step - loss: 0.0061
Epoch 8/20
844338/844338 [==============================] - 179s 212us/step - loss: 0.0060
Epoch 9/20
844338/844338 [==============================] - 180s 213us/step - loss: 0.0059
Epoch 10/20
844338/844338 [==============================] - 180s 213us/step - loss: 0.0059
Epoch 11/20
844338/844338 [==============================] - 179s 212us/step - loss: 0.0058
Epoch 12/20
844338/844338 [==============================] - 179s 212us/step - loss: 0.0057
Epoch 13/20
844338/844338 [==============================] - 180s 213us/step - loss: 0.0057
Epoch 14/20
844338/844338 [==============================] - 179s 212us/step - loss: 0.0056
Epoch 15/20
844338/844338 [==============================] - 179s 212us/step - loss: 0.0056
Epoch 16/20
844338/844338 [==============================] - 180s 213us/step - loss: 0.0056
Epoch 17/20
844338/844338 [==============================] - 180s 213us/step - loss: 0.0055
Epoch 18/20
844338/844338 [==============================] - 181s 214us/step - loss: 0.0055
Epoch 19/20
844338/844338 [==============================] - 180s 213us/step - loss: 0.0055
Epoch 20/20
844338/844338 [==============================] - 180s 213us/step - loss: 0.0055

In [0]:
save_model(NN, 'NN_list_train_epochs20_batch_size128_loss0055_scorekaggle_012616')

In [190]:
df_train.head()

,Store,DayOfWeek,Year,Month,Day,StateHoliday,CompetitionMonthsOpen,Promo2Weeks,StoreType,Assortment,...,Min_Humidity,Max_Wind_SpeedKm_h,Mean_Wind_SpeedKm_h,CloudCover,trend,trend_DE,AfterStateHoliday,BeforeStateHoliday,Promo,SchoolHoliday
Date,,,,,,,,,,,,,,,,,,,,,
2015-07-31,1,5,3,7,31,1,25,1,3,1,...,-1.620066,0.149027,-0.142774,-1.844823,1.732493,1.724336,0.604460,1.13112,1.113717,2.04105
2015-07-31,2,5,3,7,31,1,25,26,1,1,...,-1.264031,-0.960613,-0.142774,-0.488722,1.294579,1.724336,0.926957,1.13112,1.113717,2.04105
2015-07-31,3,5,3,7,31,1,25,26,1,1,...,-1.314893,-0.960613,-1.154031,-1.392789,1.820076,1.724336,0.604460,1.13112,1.113717,2.04105
2015-07-31,4,5,3,7,31,1,25,1,3,3,...,-1.009721,0.038063,0.699941,0.415345,0.769082,1.724336,0.926957,1.13112,1.113717,2.04105
2015-07-31,5,5,3,7,31,1,4,1,1,1,...,-1.213169,-0.960613,-0.142774,-0.488722,1.469744,1.724336,0.604460,1.13112,1.113717,2.04105

In [0]:
def make_prediction(model, df):
  
    list_df = convert_df_to_nn_format(df)
    pred_yl = model.predict(list_df)
    pred_y = inv_yl_for_pred(pred_yl)
    
    return pred_y

In [0]:
y_test = make_prediction(NN, df_test)

In [197]:
generate_sub_file(y_test, 'sub_list_train_epochs20_batch_size128_loss0055')

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:357: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s